spring:
  application:
    name: spring-boot-environment-variables-demo

xyz:
  config:
    feature-flags:
      myProperty: false
      rtme-2101-audit-logs: true
      rtme-1470-multi-edit: "345678"

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - env

